#!/bin/bash
# Handy script for launching a program under gdb, whilst wiring up gdb to use
# the working copy of gdb-heap
# Typical usage:
#   ./run-gdb-heap python
PYTHONPATH="$(pwd)" \
  gdb \
  --eval-command="python import gdbheap" \
  --args $*
